-- Integra hesap güvenliği temeli
-- 1) Personel hesaplarını Supabase Auth UUID'sine bağlar.
-- 2) Oturum sahibine yalnızca kendi güvenli profilini döndüren RPC'yi ekler.
-- 3) Herkese açık QR menüde hesap tablosunu açmadan işletme adını döndürür.
-- 4) Eski hesapların ilk giriş geçişi için hız sınırı kayıtlarını hazırlar.
--
-- Bu migration erişim politikalarını henüz kapatmaz. Önce yeni uygulama ve
-- Edge Function yayına alınır; ardından account_lockdown migration'ı çalıştırılır.

create schema if not exists private;

alter table public.personeller
  add column if not exists auth_user_id uuid;

create unique index if not exists personeller_auth_user_id_unique
  on public.personeller (auth_user_id)
  where auth_user_id is not null;

create unique index if not exists restaurants_owner_email_unique
  on public.restaurants (lower(btrim(email)))
  where nullif(btrim(email), '') is not null
    and coalesce(rol, 'owner') = 'owner';

create unique index if not exists personeller_email_unique
  on public.personeller (lower(btrim(email)))
  where nullif(btrim(email), '') is not null;

create table if not exists public.integra_auth_deneme_loglari (
  id bigint generated by default as identity primary key,
  email_hash text not null,
  ip_hash text not null,
  basarili boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists integra_auth_deneme_loglari_kontrol_idx
  on public.integra_auth_deneme_loglari (email_hash, ip_hash, created_at desc);

alter table public.integra_auth_deneme_loglari enable row level security;
revoke all on table public.integra_auth_deneme_loglari from public, anon, authenticated;
revoke all on sequence public.integra_auth_deneme_loglari_id_seq from public, anon, authenticated;
grant all on table public.integra_auth_deneme_loglari to service_role;
grant usage, select on sequence public.integra_auth_deneme_loglari_id_seq to service_role;

create or replace function private.integra_restaurant_id()
returns bigint
language sql
stable
security definer
set search_path = ''
as $$
  select eslesme.restaurant_id
  from (
    select coalesce(r.parent_restaurant_id, r.id) as restaurant_id, 1 as oncelik
    from public.restaurants r
    where r.auth_user_id = (select auth.uid())
      and r.durum = 'Aktif'

    union all

    select p.restaurant_id, 2 as oncelik
    from public.personeller p
    join public.restaurants r
      on r.id = p.restaurant_id
     and coalesce(r.rol, 'owner') = 'owner'
    where p.auth_user_id = (select auth.uid())
      and p.durum = 'Aktif'
      and r.durum = 'Aktif'
  ) eslesme
  order by eslesme.oncelik
  limit 1
$$;

revoke all on function private.integra_restaurant_id() from public, anon, authenticated;
grant execute on function private.integra_restaurant_id() to authenticated, service_role;

create or replace function public.integra_oturum_profili()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_sonuc jsonb;
begin
  select (to_jsonb(r) - 'password') || jsonb_build_object(
    'hesap_tipi', 'owner'
  )
  into v_sonuc
  from public.restaurants r
  where r.auth_user_id = (select auth.uid())
    and coalesce(r.rol, 'owner') = 'owner'
  limit 1;

  if v_sonuc is not null then
    return v_sonuc;
  end if;

  select jsonb_build_object(
    'id', p.id,
    'email', p.email,
    'name', p.ad,
    'restaurant_name', coalesce(r.restaurant_name, r.name),
    'waiter_name', p.ad,
    'durum', case
      when p.durum = 'Aktif' and r.durum = 'Aktif' then 'Aktif'
      else coalesce(nullif(p.durum, 'Aktif'), r.durum, 'Pasif')
    end,
    'rol', 'waiter',
    'role', 'waiter',
    'parent_restaurant_id', r.id,
    'personel_id', p.id,
    'personel_gorev', coalesce(p.gorev, 'Garson'),
    'gorev', coalesce(p.gorev, 'Garson'),
    'tab_yetkileri', coalesce(p.tab_yetkileri, '[]'::jsonb),
    'aktif_sekmeler', coalesce(r.aktif_sekmeler, '[]'::jsonb),
    'modul_paketi', coalesce(r.modul_paketi, r.paket_adi, r.basvuru_paketi, 'Premium'),
    'paket_adi', coalesce(r.paket_adi, r.basvuru_paketi, 'Premium'),
    'basvuru_paketi', coalesce(r.basvuru_paketi, r.paket_adi, 'Premium'),
    'kullanici_limiti', coalesce(r.kullanici_limiti, 3),
    'hesap_tipi', 'personel'
  )
  into v_sonuc
  from public.personeller p
  join public.restaurants r
    on r.id = p.restaurant_id
   and coalesce(r.rol, 'owner') = 'owner'
  where p.auth_user_id = (select auth.uid())
  limit 1;

  return v_sonuc;
end;
$$;

revoke all on function public.integra_oturum_profili() from public, anon;
grant execute on function public.integra_oturum_profili() to authenticated, service_role;

create or replace function public.integra_qr_menu_isletmesi(p_restaurant_id bigint)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'id', r.id,
    'name', coalesce(r.name, r.restaurant_name, 'Dijital Menü'),
    'restaurant_name', coalesce(r.restaurant_name, r.name, 'Dijital Menü'),
    'isletme_tipi', coalesce(r.isletme_tipi, 'Restoran')
  )
  from public.restaurants r
  where r.id = p_restaurant_id
    and coalesce(r.rol, 'owner') = 'owner'
    and r.durum = 'Aktif'
  limit 1
$$;

revoke all on function public.integra_qr_menu_isletmesi(bigint) from public;
grant execute on function public.integra_qr_menu_isletmesi(bigint) to anon, authenticated, service_role;

comment on function public.integra_oturum_profili()
  is 'Geçerli Supabase Auth oturumuna ait owner veya personel profilini parola alanı olmadan döndürür.';

comment on function public.integra_qr_menu_isletmesi(bigint)
  is 'QR menü için yalnızca herkese açık işletme kimliği ve adını döndürür.';
