-- Cari kartlarini musteri/tedarikci gruplarina ayirir ve fatura bilgilerini saklar.

begin;

create table if not exists public.cari_gruplari (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  grup_adi text not null,
  grup_turu text not null default 'musteri',
  sira integer not null default 0,
  aktif boolean not null default true,
  created_at timestamptz not null default now(),
  constraint cari_gruplari_grup_adi_check check (length(btrim(grup_adi)) between 1 and 100),
  constraint cari_gruplari_grup_turu_check check (grup_turu in ('musteri', 'tedarikci', 'karma'))
);

create unique index if not exists cari_gruplari_restaurant_adi_unique
  on public.cari_gruplari (restaurant_id, lower(btrim(grup_adi)));

create index if not exists cari_gruplari_restaurant_sira_idx
  on public.cari_gruplari (restaurant_id, sira, grup_adi);

alter table public.cari_musteriler
  add column if not exists cari_grup_id bigint references public.cari_gruplari(id) on delete set null,
  add column if not exists cari_tipi text not null default 'musteri',
  add column if not exists vergi_no text,
  add column if not exists vergi_dairesi text,
  add column if not exists adres text;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'cari_musteriler_cari_tipi_check'
      and conrelid = 'public.cari_musteriler'::regclass
  ) then
    alter table public.cari_musteriler
      add constraint cari_musteriler_cari_tipi_check
      check (cari_tipi in ('musteri', 'tedarikci', 'karma'));
  end if;
end $$;

create index if not exists cari_musteriler_grup_idx
  on public.cari_musteriler (restaurant_id, cari_grup_id, ad);

insert into public.cari_gruplari (restaurant_id, grup_adi, grup_turu, sira)
select r.id, varsayilan.grup_adi, varsayilan.grup_turu, varsayilan.sira
from public.restaurants r
cross join (
  values ('Müşteriler', 'musteri', 10), ('Tedarikçiler', 'tedarikci', 20)
) as varsayilan(grup_adi, grup_turu, sira)
on conflict do nothing;

update public.cari_musteriler c
set cari_grup_id = g.id,
    cari_tipi = 'musteri'
from public.cari_gruplari g
where c.cari_grup_id is null
  and g.restaurant_id = c.restaurant_id
  and g.grup_adi = 'Müşteriler';

-- Yalnızca alış faturalarında kullanılmış eski carileri tedarikçi grubuna taşır.
update public.cari_musteriler c
set cari_grup_id = g.id,
    cari_tipi = 'tedarikci'
from public.cari_gruplari g
where g.restaurant_id = c.restaurant_id
  and g.grup_adi = 'Tedarikçiler'
  and exists (
    select 1 from public.market_alis_faturalari f
    where f.restaurant_id = c.restaurant_id and f.cari_id = c.id::text
  )
  and not exists (
    select 1 from public.market_satislari s
    where s.restaurant_id = c.restaurant_id and s.cari_id = c.id::text
  );

create or replace function public.cari_varsayilan_gruplari_olustur()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.cari_gruplari (restaurant_id, grup_adi, grup_turu, sira)
  values
    (new.id, 'Müşteriler', 'musteri', 10),
    (new.id, 'Tedarikçiler', 'tedarikci', 20)
  on conflict do nothing;
  return new;
end;
$$;

drop trigger if exists restaurants_cari_varsayilan_gruplari_trigger on public.restaurants;
create trigger restaurants_cari_varsayilan_gruplari_trigger
after insert on public.restaurants
for each row execute function public.cari_varsayilan_gruplari_olustur();

alter table public.cari_gruplari enable row level security;

grant select, insert, update, delete on table public.cari_gruplari to authenticated;
grant usage, select on sequence public.cari_gruplari_id_seq to authenticated;

drop policy if exists cari_gruplari_restaurant_policy on public.cari_gruplari;
create policy cari_gruplari_restaurant_policy
  on public.cari_gruplari
  for all
  to authenticated
  using (restaurant_id = (select private.integra_restaurant_id()))
  with check (restaurant_id = (select private.integra_restaurant_id()));

comment on table public.cari_gruplari is 'Müşteri, tedarikçi ve karma cari grupları';
comment on column public.cari_musteriler.vergi_no is 'TCKN veya vergi kimlik numarası';
comment on column public.cari_musteriler.vergi_dairesi is 'Cari vergi dairesi';
comment on column public.cari_musteriler.adres is 'Cari fatura ve teslimat adresi';

notify pgrst, 'reload schema';
commit;
